### ISSUE TITLE
为什么没有setNewData这类方法？

### ISSUE THREAD

**Issue by Blankeer** [byteam/SuperAdapter#11]
分页加载，下拉刷新，把原先的数据全部移除，再添加新内容。
只能用clear()再addAll()曲线救国，而且clear()会报错

```
Inconsistency detected. Invalid view holder adapter positionViewHolder
```

只能再重新调用下notifyDataSetChanged()才避免报错。
相关代码如下：

```
@Override
    public void setData(List<Article> data) {
        if (page == 0) {
            mArticles.clear();
            mAdapter.clear();
            mAdapter.notifyDataSetChanged();//不要这句会报错
        }
        mArticles.addAll(data);
        mAdapter.addAll(data);
        page++;
        stopRefreLoad();
    }
```

**Comment by chenenyu** [comment]
不需要操作mArticles，仅需要变动mAdapter即可。你可以尝试mAdapter.replaceAll方法，一行代码足矣。

**Comment by Blankeer** [comment]
感谢回答，已经解决问题了，源码看的不够仔细，replaceAll()类似于setNewData()方法。我的代码中mArticles只是做个备份，无关紧要。另:我单独测试了下mAdapter.clear()清空Adapter数据，会报错`java.lang.IndexOutOfBoundsException:   Inconsistency detected. Invalid view holder adapter positionViewHolder`，不知是我使用姿势不对，还是什么原因。

**Comment by chenenyu** [comment]
备份不是很有必要，如果你需要查看数据源，可以使用mAdapter.getList()查看当前数据集合。至于clear()崩溃，应该不太可能是源码问题，我会尽快再做一些相关测试，如有结果，会告知与您。谢谢反馈。

**Comment by chenenyu** [comment]
经查证`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder`是RecyclerView自身的一个bug，详见[issue](https://code.google.com/p/android/issues/detail?id=77846)，现有几种解决方式：  
1. 通过继承各种`LayoutManager`捕获这个异常，如   

```
public class MyLayoutManager extends LinearLayoutManager {
    public MyLayoutManager(Context context) {
        super(context);
    }

    public MyLayoutManager(Context context, int orientation, boolean reverseLayout) {
        super(context, orientation, reverseLayout);
    }

    public MyLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        try {
            super.onLayoutChildren(recycler, state);
        } catch (Exception e) {
            Log.d("MyLayoutManager", "onLayoutChildren: " + e.toString());
        }
    }
}
```

这种方式略微麻烦。
2. 在您自己的Adapter中重写`SuperAdapter`中的`clear()`方法，如:

```
    @Override
    public final void clear() {
        if (!mList.isEmpty()) {
            mList.clear();
            notifyDataSetChanged();  // RecyclerView
            notifyDataSetHasChanged(); // AdapterView
        }
    }
```

这种方式的缺陷是清空数据时不会执行动画，如果您不使用动画，可以采用这种方式。
3.  更新版本，v3.4将会采用第二种方式暂时解决这个问题。您可以根据自己的需求采用合理的方式。  欢迎继续反馈~
