### ISSUE TITLE
在 index=0 的位置插入数据无法直接添加 item

### ISSUE THREAD

**Issue by MrTrying** [byteam/SuperAdapter#12]
调用 `mAdapter.add(0,map);` 之后无法直接添加 item

**Comment by chenenyu** [comment]
是add还是addAll呢？

**Comment by MrTrying** [comment]
我是用的是这个方法`add(0,item)`，这个插入的数据是成功的，但是没有马上显示出来

具体的情况我描述一下，
情况一：当`RecycleView`中的item没有站满整个屏幕的时候，`add(0,item)`方法是有效的
情况二：当`RecycleView`中的item的数量比较多的时候，已经超出屏幕了，再调用`add(0,item)`方法时无法看到第一个item直接显示出来，当向下滑动`RecycleView`时，刚才加入的item会显示出来
情况三：当我使用`mAdapter.addHeader(view)`方法添加一个headerView之后，调用`add(0,item)`方法是没有任何问题的。

此外我i还在`RecycleView`的外层使用了该下拉刷新框架[https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh)

以上是我可以提供的信息。

**Comment by chenenyu** [comment]
我等会测试一下，请稍候。谢谢反馈。

**Comment by chenenyu** [comment]
您的意思是RecyclerView没有自动滚动上顶部吗？添加数据时，默认是不会改变可滚动控件的当前显示区域的。您可以在`add(0, item)`后使用`recyclerView.scrollToPosition(0);`来显示您插入的单条数据。

**Comment by MrTrying** [comment]
可以了，谢谢！
但是这个问题是否可以在adapter的内部解决一下。

**Comment by chenenyu** [comment]
每个人的需求都不一样，需要您自己处理哦。就比如addAll之后，列表不应该滚动到最后一样。

**Comment by MrTrying** [comment]
有道理
