### ISSUE TITLE
ViewHolder里面添加自己想要的方法

### ISSUE THREAD

**Issue by LuoGuoXin** [byteam/SuperAdapter#13]
ViewHolder，如果要添加自己的方法咋办，比如用第三方加载图片的，setImgUrl()

**Comment by chenenyu** [comment]
我会考虑您的想法，下个工作日会思考解决方案。

**Comment by chenenyu** [comment]
您好，经评估，如果支持自定义ViewHolder，情况会比`getView(int id)`然后`setImageUrl()`复杂的多，得不偿失，如果您有好的实现方式，欢迎提交issue或者request。
