### ISSUE TITLE
期待增加以下几个功能

### ISSUE THREAD

**Issue by LuoGuoXin** [byteam/SuperAdapter#14]
添加加载动画
上拉加载
设置自定义的加载更多布局
设置空布局

**Comment by chenenyu** [comment]
一下子给我加了一个月的工作量~~~

**Comment by ByteRax** [comment]
如果增加了这些 功能，就违背Adapter的初衷了。
关于加载动画：https://github.com/Syehunter/MaterialPageStateLayout
上拉加载 设置自定义的加载更多布局：https://github.com/pengjianbo/LoadingViewFinal
设置空布局：https://github.com/Syehunter/MaterialPageStateLayout
专业的事情交给专业的库，功能太多就臃肿了。

**Comment by chenenyu** [comment]
@tanranran 感谢您的分享 💯
