### ISSUE TITLE
3.1->3.2 更新了什么东西？

### ISSUE THREAD

**Issue by Wing-Li** [byteam/SuperAdapter#15]
之前用的 3.0.0 直接更新到3.3下拉刷新出错了，
列表增加了Header，

试了几次之后，发现是 3.1 - > 3.2 出错。

![image](https://cloud.githubusercontent.com/assets/12133489/16258678/7a798d68-3891-11e6-9606-ee9875d2192e.png)

**Comment by chenenyu** [comment]
应该是position用错了，能贴一下相关代码吗？

**Comment by Wing-Li** [comment]
@chenenyu 代码就没有动，只更换了build.gradle 的包名。

就是这个项目：
https://github.com/Wing-Li/boon

把 build.gradle 3.1 更换 成 3.2 以上就出错了。

在网上搜了搜，好像是 RecyclerView 的问题。
http://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in

**Comment by chenenyu** [comment]
参见#11 这是RV本身的bug。

**Comment by Wing-Li** [comment]
@chenenyu OK,非常感谢
