### ISSUE TITLE
加载网络图片

### ISSUE THREAD

**Issue by zuoer8676** [byteam/SuperAdapter#16]
在viewholder怎样加载网络图片？demo中没有。

**Comment by chenenyu** [comment]
通过`ImageView img = holder.findViewById(id);`拿到`ImageView`，然后用你项目本身的图片加载库加载网络图片。因为每个人用到的库不一样，有Fresco，有UIL，有Glide等等，所以留给自己做咯。

**Comment by nocb** [comment]
感谢  正要问呢
