### ISSUE TITLE
bug真的有点多...

### ISSUE THREAD

**Issue by vwo50u** [byteam/SuperAdapter#17]
,

**Comment by dursss** [comment]
最让人难受的是,上面说到的所有bug都不定期不定点出现,这会是好的,过一会就崩溃,或者说在这里是好的,等会到了别的地方就崩溃,唉

**Comment by chenenyu** [comment]
是不是使用有问题呢。。。   项目在用户量千万级的生产环境中检验过，也有很多其他朋友在使用该项目。 建议更新到最新版本并看下中文文档。

**Comment by dursss** [comment]
恩,正在查问题,之前项目是外包出去的,所以你懂的~~,谢谢回复

**Comment by chenenyu** [comment]
有任何问题欢迎提Issue，基本上都是使用有问题。也可以加入企鹅群交流，群号在项目主页。

**Comment by dursss** [comment]
恩好的,谢谢

**Comment by vwo50u** [comment]
1
