### ISSUE TITLE
RecyclerView怎样更改当前item的值？

### ISSUE THREAD

**Issue by 0xm1nam0** [byteam/SuperAdapter#18]
在弄 购物车点击增加num++，想要保存当前的值
以下方法会报错
               item.setNum(num);
                set(layoutPosition,item);
以下方法没效果
                mData.get(layoutPosition).setNum(num);
本来3.1版本，更换3.6版本还是这样

**Comment by chenenyu** [comment]
SuperAdapter提供了便捷方法: `mAdapter.set(int position, T item)`，或者`mAdapter.set(T oldItem, T newItem)`。 你是这么用的吗？

**Comment by 0xm1nam0** [comment]
我是在SuperAdapter的onBind方法里面view的事件监听使用的
mSv1.setOnShoppingClickListener(new ShoppingView.ShoppingClickListener() {
            @Override
            public void onAddClick(int num) {
                Log.d("@=>", "add.......num=> " + num);
                item.setNum(num);
                mData.get(layoutPosition).setNum(num);
//                set(layoutPosition,item);
            }

```
        @Override
        public void onMinusClick(int num) {
            Log.d("@=>", "minus.......num=> " + num);
            item.setNum(num);
            mData.get(layoutPosition).setNum(num);
```

//                set(layoutPosition,item);
            }
        });

**Comment by 0xm1nam0** [comment]
mAdapter.set(int position, T item)报错
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
参考http://blog.csdn.net/qq199208/article/details/50436873
在滑动或者计算layout的时候不刷新数据: 
ShoppingView点击的时候有动画的https://github.com/JeasonWong/ElemeShoppingView

**Comment by chenenyu** [comment]
把layoutPosition换成`holder.getAdapterPosition()`试试呢？   我再看看你的问题

**Comment by chenenyu** [comment]
你的问题不是SuperAdapter的bug，而是用错误的方式使用了RV，在onBind阶段最好不要做点击事件的绑定，在有动画的情况下会报状态异常。我想到了2种解决方案：  
1. 使用`handler`更新数据
2. 在`onCreate()`中做事件的绑定(推荐)

```
@Override
    public SuperViewHolder onCreate(View convertView, ViewGroup parent, int viewType) {
        SuperViewHolder holder = super.onCreate(convertView, parent, viewType);
        holder.findViewById(id).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // just like this, good luck!
            }
        });
        return holder;
    }
```

**Comment by 0xm1nam0** [comment]
ok,thx.我解决了问题。

**Comment by chenenyu** [comment]
是按方式2解决的么~
