### ISSUE TITLE
Error:(29, 13) Failed to resolve: org.byteam.superadapter:superadapter:latestVersion

### ISSUE THREAD

**Issue by XinYiWorld** [byteam/SuperAdapter#20]

**Comment by chenenyu** [comment]
`compile 'org.byteam.superadapter:superadapter:3.6.1'`

**Comment by XinYiWorld** [comment]
thanks ,@chenenyu,it worked for me.

**Comment by chenenyu** [comment]
Feel free to contact me, please star this repo if you like it.
