### ISSUE TITLE
addAll 方法里面增加一个清空并添加的方法

### ISSUE THREAD

**Issue by ByteRax** [byteam/SuperAdapter#21]
addAll（List<T> items，Boolean isClear）

如果isClear是true，那么就先把之前的items清空，然后在把最新的items赋值给items。

这个方法在下拉刷新和上拉加载的时候，用的特别平凡。  下拉刷新的时候就得把之前的集合全清空，然后把最新的数据赋值给List items，而当上拉加载的时候就是不清空，在老数据之后添加数据

**Comment by chenenyu** [comment]
adapter的所有便捷方法目前都和`List`保持一致，包括`addAll`，如果是加载更多，可以用`replaceAll`。

**Comment by ByteRax** [comment]
@chenenyu  replaceAll 不行，比如我有第一页的数据  和第二页的数据，这时候我下拉刷新。如果用replaceAll的话，第一页确实替换了，但是第二页的数据还在。

实际的下拉刷新是，比如你目前在第二页 ，一刷新那么 第二页和第一页的数据都没了。直接显示最新的第一页的数据。

**Comment by chenenyu** [comment]
`replaceAll` 会先清空所有数据，demo里有`replaceAll`的使用，建议先看下。

**Comment by ByteRax** [comment]
好的。三克油。
