### ISSUE TITLE
以非常快的速度点击的时候，得到的position可能会是-1

### ISSUE THREAD

**Issue by gitwizChen** [byteam/SuperAdapter#24]
可以在item点击上防抖动

**Comment by gitwizChen** [comment]
刚试了一下，防抖动也没用。估计是动画的原因，返回的mLastPosition有问题吧？

**Comment by chenenyu** [comment]
你好，能提供一下具体的操作流程么，如何复现。

**Comment by gitwizChen** [comment]
@chenenyu 就是我用了这个adapter实现了一个GridLayout的RecyclerView，然后就很快的乱点，就会出现返回的position==-1的异常，这个你可以写一个简单的这样的RecyclerView测试一下。
