### ISSUE TITLE
提个场景不知道这样的改进好不好

### ISSUE THREAD

**Issue by hkq325800** [byteam/SuperAdapter#25]
fragment中含list使用superAdapter 发起请求迅速finish activity会报"getSystemService"on a null object reference明显是context为空了导致LayoutInflater.from(context)的crash

改进方法:在LayoutInflater.from(context)前判空 否则的话我现在都是在new xxAdapter前判空 还挺麻烦的

**Comment by chenenyu** [comment]
`LayoutInflater.from(context)`是必须要提供一个非null的context的，否则的话没有Inflater就不能正常工作了，如果你是`getActivity()`返回`null`，建议自己处理下这种问题，比如http://stackoverflow.com/questions/11631408/android-fragment-getactivity-sometime-returns-null
