### ISSUE TITLE
用了这个适配器，Item点击的水波纹效果消失了。。。

### ISSUE THREAD

**Issue by zhangzhichaolove** [byteam/SuperAdapter#26]
5.0版本默认支持的水波纹效果没了- -

**Comment by chenenyu** [comment]
你是说Ripple效果？这个库不影响视觉效果的。

**Comment by zhangzhichaolove** [comment]
我看了源码，原理上应该是没影响的，可是没了，对了链式调用这块能不能改下呢，小建议，例如：
`    if (viewType == 0) {
                holder.view(R.id.tv).setText(item).setTextColor(Color.BLACK);
                holder.view(R.id.bt).setText(item).setTextColor(Color.RED).setTextSize(20);
            } else if (viewType == 1) {
                holder.view(R.id.tv).setText(item).setTextColor(Color.BLACK);
                holder.view(R.id.bt).setText(item).setTextColor(Color.RED).setTextSize(20);
                holder.view(R.id.iv).setBackgroundResource(R.drawable.loader_wjz);
            }`

**Comment by chenenyu** [comment]
谢谢反馈  我再思考下实用性，欢迎加群讨论。

**Comment by zhangzhichaolove** [comment]
每设置一个属性就找一次ID，在需要设置多个属性时候难免有点麻烦，保留原来findViewById，另多加一个链式方法，连点会创建一个装饰对象，会有一定内存浪费，所以只设置单属性还是用以前的方法，需要链式的时候再生产对象，满足需求，我这边已经改动过，如有需要可参考，感谢你的开源精神。
一直是在csdn和码云，刚迁移过来，加群标准目前没满足- -
