### ISSUE TITLE
在demo里 listview set SingleAdapter后  在SuperViewHolder里绑定事件时 holder.getAdapterPosition() 一直是-1

### ISSUE THREAD

**Issue by liuxing1992** [byteam/SuperAdapter#28]
03-29 15:41:50.207 2997-2997/org.byteam.superadapter D/onClick: -1
03-29 15:41:51.775 2997-2997/org.byteam.superadapter D/onClick: -1
03-29 15:41:52.994 2997-2997/org.byteam.superadapter D/onClick: -1
03-29 15:41:54.662 2997-2997/org.byteam.superadapter D/onClick: -1
03-29 15:42:09.691 2997-2997/org.byteam.superadapter D/onClick: -1

**Comment by chenenyu** [comment]
`holder.getAdapterPosition()`是RecyclerView的方法

**Comment by liuxing1992** [comment]
那怎么获取我点击的position

**Comment by chenenyu** [comment]
listview.setOnItemClickListener

**Comment by liuxing1992** [comment]
@Override
    public SuperViewHolder onCreate(View convertView, ViewGroup parent, int viewType) {
        // These code show how to add click listener to item view of ViewHolder.
        final SuperViewHolder holder = super.onCreate(convertView, parent, viewType);

        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("onClick", "" + holder.getAdapterPosition());
            }
        });
        holder.itemView.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                Toast.makeText(getContext(), ((TextView) (holder.findViewById(R.id.tv_name))).getText(), Toast.LENGTH_SHORT).show();
                return true;
            }
        });

        return holder;
    }
这里面可以吗

**Comment by chenenyu** [comment]
RecyclerView可以在这里面获取position，listview不行，还是建议使用RecyvlerView

**Comment by chenenyu** [comment]
而且RecyclerView添加点击事件，最好使用adapter.setOnItemClickListener

**Comment by liuxing1992** [comment]
我就是怕在item里面给子view添加事件要用到position

**Comment by chenenyu** [comment]
所以使用RecyclerView吧， 安全无痛苦

**Comment by liuxing1992** [comment]
好的 最后 在onbind()里绑定事件有什么不好么

**Comment by chenenyu** [comment]
会重复绑定

**Comment by liuxing1992** [comment]
👌 知道了 谢谢
