### ISSUE TITLE
setOnClickListener Position为-1

### ISSUE THREAD

**Issue by luo4567** [byteam/SuperAdapter#29]
![image](https://user-images.githubusercontent.com/7789211/29305044-0cc9440c-81c9-11e7-8e19-f47db6568e5d.png)
![image](https://user-images.githubusercontent.com/7789211/29305046-10c52ae4-81c9-11e7-911c-2c2d33f252d1.png)

**Comment by chenenyu** [comment]
ListView or RV?

**Comment by luo4567** [comment]
就你的Demo里面的，ListView

**Comment by chenenyu** [comment]
ListView 用正常的设置监听的方式。

**Comment by luo4567** [comment]
莫名其妙
