### ISSUE TITLE
LinearLayoutManager footView宽度不能占全屏

### ISSUE THREAD

**Issue by 0xm1nam0** [byteam/SuperAdapter#3]
LinearLayoutManager footView宽度不能占全屏
用
StaggeredGridLayoutManager SGlayoutManager = new StaggeredGridLayoutManager(1, StaggeredGridLayoutManager.VERTICAL);
代替后上拉加载更多后报错，LinearLayoutManager 可以正常上拉加载更多
java.lang.ArrayIndexOutOfBoundsException
src.length=11 srcPos=10 dst.length=11 dstPos=20 length=-9
java.lang.System.arraycopy(Native Method)

**Comment by 0xm1nam0** [comment]
StaggeredGridLayoutManager  footView宽度能占全屏，但是上拉加载更多后报错

**Comment by chenenyu** [comment]
@WeissWill 
**LinearLayoutManager footView宽度不能占全屏**   你的footerView可以设置LayoutParams.MATCH_PARENT.   **StaggeredGridLayoutManager加载更多报错**，请问是通过adapter.addAll等方法改变数据源的吗？

**Comment by 0xm1nam0** [comment]
@chenenyu 是通过adapter.addAll改变数据源

**Comment by chenenyu** [comment]
@WeissWill 好的，我将尽快查证，如果有问题，会尽快修复并通知你 : )

**Comment by 0xm1nam0** [comment]
谢谢！LinearLayoutManager footView设置LayoutParams.MATCH_PARENT已经解决问题了。
至于StaggeredGridLayoutManager只是个替代方案，不用急: )
