### ISSUE TITLE
最新版怎么添加 - - 

### ISSUE THREAD

**Issue by Wing-Li** [byteam/SuperAdapter#4]
compile 'org.byteam.superadapter:superadapter:3.0.0-alpha1'
或者
 compile 'org.byteam.superadapter:superadapter:3.0.0'

都不可以。

**Comment by chenenyu** [comment]
Hello Wing-Li,
    Try compile 'org.byteam.superadapter:superadapter:3.0.0-alpha1@aar’ (add @aar at last).
    I hope this clarifies.
    Feel free to contact me for any other question.

> 在 2016年4月6日，16:48，Wing-Li notifications@github.com 写道：
> 
> compile 'org.byteam.superadapter:superadapter:3.0.0-alpha1'

**Comment by Wing-Li** [comment]
@chenenyu 
That‘s ok，thanks
