### ISSUE TITLE
关于item的填充损耗问题

### ISSUE THREAD

**Issue by panpeng0014** [byteam/SuperAdapter#6]
在源码中我看到onCreate()方法的具体实现的是偶发现，每一次都会根据layoutId来inflate一个view，但是每次inflate这个view就会产生损耗，而且能够复用convertView的时候也会inflate这个view。

**Comment by chenenyu** [comment]
感谢您的关注，ListView确实会存在一些损耗，我会尽快改进。如果您有什么好的建议，可以提出来哦~

**Comment by panpeng0014** [comment]
我一直不太理解，onCreateViewHolder这个方法，在item被复用的时候会不会被调用？

**Comment by chenenyu** [comment]
`onCreateViewHolder`只会在创建item的时候调用，或者布局发生改变需要重新绘制的时候才会再次调用。复用的时候是不会再次调用的。

**Comment by panpeng0014** [comment]
刚刚看了下recyclerView.adapter的源码，明白了，谢谢

**Comment by chenenyu** [comment]
已优化，欢迎提供更多建议。 : )
