### ISSUE TITLE
RecyclerView ItemAnimator无效

### ISSUE THREAD

**Issue by ByteRax** [byteam/SuperAdapter#8]
如题

**Comment by chenenyu** [comment]
如果方便的话，请贴一下关键代码。

**Comment by ByteRax** [comment]
recyclerView=getView(R.id.listView);
        mPtrLayout=getView(R.id.ptr_rv_layout);
        homeAdapter=new HomeAdapter(context,new ArrayList<String>(),R.layout.list_item_home);
        recyclerView.setAdapter(homeAdapter);
        StatusBarUtils.processActionBar(getView(R.id.toolbar),true);
        recyclerView.setItemAnimator(newDefaultItemAnimator());
        for (int i=0;i<10;i++){
            homeAdapter.add("fsaf");
        }

**Comment by chenenyu** [comment]
这个for循环，根本来不及做动画吧
