### ISSUE TITLE
建议增加一个 清空数据重新添加数据的方法

### ISSUE THREAD

**Issue by ByteRax** [byteam/SuperAdapter#9]
有一种场景是大多数人都会遇到,下拉刷新的时候....会先清空适配器里面的所有 数据,然后在重新添加最新的数据....SuperAdapter  就会先clear  notifyDataSetChanged一次,然后addall  会在次调用notifyDataSetChanged 一次...所以添加一个这样的方法可以少调用一次notifyDataSetChanged

**Comment by chenenyu** [comment]
`replaceAll(list)`  先用这个替代吧，虽然会notify两次 囧~  我会在近期优化这个方法的实现，谢谢反馈

**Comment by ByteRax** [comment]
嗯嗯.

**Comment by chenenyu** [comment]
Hi, I just released [v3.2](https://github.com/byteam/SuperAdapter/releases/tag/v3.2) which optimizes actions about `notify`. Welcome to have a try.
